// Placeholder Firebase configuration.
//
// This file is normally generated by running `flutterfire configure` (after
// creating a Firebase project in the console and running
// `dart pub global activate flutterfire_cli`). That command overwrites this
// file with real values and downloads android/app/google-services.json.
//
// Until that has been run, Firebase.initializeApp() will fail with these
// placeholder values - main.dart catches that and simply skips crash
// reporting, so the app runs normally either way.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this app targets Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android. '
          'Run `flutterfire configure` to add other platforms.',
        );
    }
  }

  /// Run `flutterfire configure` to replace these with real project values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    storageBucket: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
  );
}
